# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - left_arm_controller
    - right_arm_controller

  left_arm_controller:
    type: FollowJointTrajectory
    joints:
      - base_link-v1_linkL1
      - link_L_1-v1_linkL2
      - link_L_2-v1_linkL3
      - link_L_3-v1_linkL4
      - link_L_4-v1_linkL5
    action_ns: follow_joint_trajectory
    default: true
  right_arm_controller:
    type: FollowJointTrajectory
    joints:
      - base_link-v1_linkR1
      - link_R_1-v1_linkR2
      - link_R_2-v1_linkR3
      - link_R_3-v1_linkR4
      - link_R_4-v1_linkR5
    action_ns: follow_joint_trajectory
    default: true